language: node_js
node_js:
  - '6'
  - '4'
script:
  - yarn run ci
cache: yarn

deploy:
  provider: npm
  email: kenneth.skovhus@gmail.com
  api_key: $NPM_TOKEN
  on:
    tags: true
    repo: skovhus/css-modules-flow-types
