'use strict';

import os from 'os';

export const HEADER = `// @flow strict
/* This file is automatically generated by css-modules-flow-types */`;

export default function printFlowDefinition(tokensArray, indent = '  ') {
  const props = tokensArray
    .sort()
    .map(key => `${indent}+'${key}': string,`)
    .join(os.EOL);

  return `${HEADER}
declare module.exports: {|
${props}
|};
`;
}
