'use strict';

import os from 'os';

export default function printFlowDefinition(tokensArray, indent = '  ') {
  const props = tokensArray
    .sort()
    .map(key => `${indent}+'${key}': string;`)
    .join(os.EOL);

  return `// @flow
/* This file is automatically generated by css-modules-flow-types */
declare module.exports: {|
${props}
|};
`;
}
