'use strict';

import os from 'os';

export default function printFlowDefinition(tokens, indent = '  ') {
  const props = Object.keys(tokens)
    .sort()
    .map(key => `${indent}+'${key}': string;`)
    .join(os.EOL);

  return `/* This file is automatically generated by css-modules-flow-typed. */
// @flow
declare module.exports: {|
${props}
|};
`;
}
